### PR TITLE
Initial exporter

### PR DESCRIPTION
**Pull request by patrickeasters**
This is an initial stab at a Prometheus exporter for file locks. It can be run directly on a node, but is intended to be run in a pod as a daemonset on worker nodes.

Tasks:
- [x] Implement exporter
- [x] Create container image build
- [x] Provide example daemonset template for running in OCP

Example metrics output
```
# HELP locks_container_file_locks Number of file locks held by processes in container
# TYPE locks_container_file_locks gauge
locks_container_file_locks{container="etcd",namespace="openshift-etcd",pod="etcd-master-0.peocp4.cloud.lab.eng.bos.redhat.com"} 1
locks_container_file_locks{container="metal3-mariadb",namespace="openshift-machine-api",pod="metal3-778c86f97f-wt7nz"} 24
locks_container_file_locks{container="nbdb",namespace="openshift-ovn-kubernetes",pod="ovnkube-master-fhjkg"} 2
locks_container_file_locks{container="northd",namespace="openshift-ovn-kubernetes",pod="ovnkube-master-fhjkg"} 1
locks_container_file_locks{container="ovn-controller",namespace="openshift-ovn-kubernetes",pod="ovnkube-node-z8vng"} 1
locks_container_file_locks{container="ovnkube-master",namespace="openshift-ovn-kubernetes",pod="ovnkube-master-fhjkg"} 1
locks_container_file_locks{container="sbdb",namespace="openshift-ovn-kubernetes",pod="ovnkube-master-fhjkg"} 2
```

### CODE REVIEW

**Comment by dcritch** [comment]
Looks good so far! Let me know when you want me to test a build on a cluster or two.

**Comment by glennswest** [comment]
Why not do this for each namespace automatically.

**Comment by patrickeasters** [comment]
This is in a better state for review now. While the crio method worked, I switched to using procfs (inspired by @dcritch's bash approach) since it avoided the need for the container to run as root or have read/write access to the node filesystem.

There are instructions for deploying the daemonset in the README. I have the image on my Quay namespace, but will look at moving that to the `rhsysdeseng` one when I get access.

**Comment by dcritch** [comment]
Ran the latest and it works for me. One suggestion: you could add a note on how to have it run on the control nodes as well. Adding this to the DaemonSet should do it:
>      tolerations:
>      - operator: Exists

**Pull request merged**
